name: Publish Docker Image

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      RELEASE_VERSION: "0.0.1-alpha"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Set up .NET6
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "6.0"

      - name: Install and Build Frontend
        run: |
          cd Frontend
          npm install
          npm run build:production

      - name: Publish Backend
        run: |
          dotnet publish -c Release --self-contained true --runtime linux-x64 -o bin/Release/net6.0/publish

      - name: Build Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository }}:${{ env.RELEASE_VERSION }} -t ghcr.io/${{ github.repository }}:latest .

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Docker image to GitHub Container Registry
        run: |
          docker push ghcr.io/${{ github.repository }}:${{ env.RELEASE_VERSION }}
          docker push ghcr.io/${{ github.repository }}:latest
